### ISSUE TITLE
Session::Storage::Secure fails against blead due to test failures in dependency Sereal::Encoder

### ISSUE THREAD

**Issue by jkeenan** [dagolden/Session-Storage-Secure#6]
Session::Storage::Secure is failing when tested against Perl 5 blead.  It's a dependency failure; tests in Sereal::Encoder are failing.  See https://github.com/Sereal/Sereal/issues/173 and https://rt.perl.org/Public/Bug/Display.html?id=131852.  The Sereal::Encoder test failures are, strictly speaking, BBC, but the way those tests are set up defies analysis by mere mortals.  Intervention by the distro maintainer will probably be needed.

```
./bin/cpanm --verbose Session::Storage::Secure
...
! Installing the dependencies failed: Module 'Sereal::Encoder' is not installed
! Bailing out the installation for Session-Storage-Secure-0.010.
8 distributions installed
```

**Comment by xdg** [comment]
Sounds like this is fixed upstream.
