### ISSUE TITLE
Crypt-CBC-3.01 warns: The key derivation method "opensslv1" is deprecated

### ISSUE THREAD

**Issue by ppisar** [dagolden/Session-Storage-Secure#8]
After upgrading Crypt-CBC to 3.01:

$ perl -MSession::Storage::Secure -e 'Session::Storage::Secure->new(secret_key=>1)->encode()'
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /usr/share/perl5/vendor_perl/Session/Storage/Secure.pm line 213.

The new CBC::Encrypt defaults to -pbkdf => 'opensslv1' to preserve compatibility and warns about that at the same time.
Session::Storage::Secure can either pass -nodeprecate=>1 to silent the warning, or pass -pbkdf => 'pbkdf2' to use stronger encryption key.
pbkdf2.

Since changing -pkbkdf makes the old encrypted data nondecryptable, Session::Storage::Secure should come up with a transition plan how to move to the stronger PBKDF (e.g with using an old_secrets-like argument). Please note that -pbkdf => 'opensslv1' uses MD5 underneath and that could become unavailable in the future OpenSSL.

I know that Session::Storage::Secure uses Digest::SHA::hmac_sha256() to populate the -key argument. And that is currently strong enough.

**Comment by xdg** [comment]
My transition plan is to introduce "protocol version 2" that can read old data. The branch is here: https://github.com/dagolden/Session-Storage-Secure/tree/v2-protocol

I'd welcome any testing/thoughts you'd like to offer before I merge and release.

**Comment by ppisar** [comment]
Thanks for the quick action. The v2-protocol code looks good. The only issue
is when a system has Crypt::CBC < 3. Then the tests fail, as well as the
original reproducer like this:

$ perl -Ilib -MSession::Storage::Secure -e 'Session::Storage::Secure->new(secret_key=>1)->encode()'
Cannot use salt-based IV generation if literal IV is specified at lib/Session/Storage/Secure.pm line 214.

If you are not going to make the new code compatible with the old Crypt::CBC,
then please increase a minimal version of Crypt::CBC in Makefile.PL.

**Comment by xdg** [comment]
Thanks for catching that.  I fixed it for 2.33 and made that the minimum.

**Comment by xdg** [comment]
Released as 0.901-TRIAL.  After I see how it smokes, I'll release it as 1.000.

**Comment by xdg** [comment]
Gave up dealing with versions of CBC::Crypt before 3.01.  Shipped S::S::S as 1.000.  Thanks again for all the help!
